import {
  Buildings, BookOpen, Users, Star, MapPin, ChartBar, Heart, GraduationCap,
  Handshake, Megaphone, Globe, Newspaper, Certificate, Tree, Scales, Lightbulb,
  Briefcase, FileText, PencilLine, Network, ArrowsCounterClockwise, Toolbox,
  PresentationChart, ClipboardText, Medal, Link, House, Microphone, Compass,
  Calendar, Flask, ChalkboardTeacher, CurrencyDollar, ArrowRight, Flag, Sparkle,
} from '@phosphor-icons/react';
import type { Icon } from '@phosphor-icons/react';

type IconComponent = Icon;

export const ICON_PALETTE: Array<{ name: string; Component: IconComponent }> = [
  { name: 'Buildings',              Component: Buildings },
  { name: 'BookOpen',               Component: BookOpen },
  { name: 'Users',                  Component: Users },
  { name: 'Star',                   Component: Star },
  { name: 'MapPin',                 Component: MapPin },
  { name: 'ChartBar',               Component: ChartBar },
  { name: 'Heart',                  Component: Heart },
  { name: 'GraduationCap',          Component: GraduationCap },
  { name: 'Handshake',              Component: Handshake },
  { name: 'Megaphone',              Component: Megaphone },
  { name: 'Globe',                  Component: Globe },
  { name: 'Newspaper',              Component: Newspaper },
  { name: 'Certificate',            Component: Certificate },
  { name: 'Tree',                   Component: Tree },
  { name: 'Scales',                 Component: Scales },
  { name: 'Lightbulb',              Component: Lightbulb },
  { name: 'Briefcase',              Component: Briefcase },
  { name: 'FileText',               Component: FileText },
  { name: 'PencilLine',             Component: PencilLine },
  { name: 'Network',                Component: Network },
  { name: 'ArrowsCounterClockwise', Component: ArrowsCounterClockwise },
  { name: 'Toolbox',                Component: Toolbox },
  { name: 'PresentationChart',      Component: PresentationChart },
  { name: 'ClipboardText',          Component: ClipboardText },
  { name: 'Medal',                  Component: Medal },
  { name: 'Link',                   Component: Link },
  { name: 'House',                  Component: House },
  { name: 'Microphone',             Component: Microphone },
  { name: 'Compass',                Component: Compass },
  { name: 'Calendar',               Component: Calendar },
  { name: 'Flask',                  Component: Flask },
  { name: 'ChalkboardTeacher',      Component: ChalkboardTeacher },
  { name: 'CurrencyDollar',         Component: CurrencyDollar },
  { name: 'ArrowRight',             Component: ArrowRight },
  { name: 'Flag',                   Component: Flag },
  { name: 'Sparkle',                Component: Sparkle },
];
