import type { UnderstoryDocument } from './types'

export const SEED_DOCUMENT: UnderstoryDocument = {
  title: 'Intersecting Processes in the Development of Community-Engaged Scholarship at IU Indianapolis',
  subtitle: 'A Taylor-inspired process map',
  startYear: 1968,
  endYear: 2026,
  eras: [
    { id: 'foundational', label: 'Foundational Urban Roots', startYear: 1968, endYear: 1992, color: '#D2BDA3' },
    { id: 'codifying', label: 'Codifying Engagement', startYear: 1993, endYear: 2005, color: '#BC7A5A' },
    { id: 'institutionalization', label: 'Institutionalization & Recognition', startYear: 2006, endYear: 2021, color: '#4B7F52' },
    { id: 'realignment', label: 'Realignment & Impact Infrastructure', startYear: 2022, endYear: 2026, color: '#3F5E78' },
  ],
  processDomains: [
    { id: 'urban', label: 'Urban Mission & Civic Identity', color: '#4E342E', order: 1 },
    { id: 'pedagogy', label: 'Pedagogy & Engaged Learning', color: '#BC7A5A', order: 2 },
    { id: 'neighborhood', label: 'Neighborhood Partnerships & Community Work', color: '#4B7F52', order: 3 },
    { id: 'scholarship', label: 'Scholarship & Public Knowledge', color: '#3F5E78', order: 4 },
    { id: 'infrastructure', label: 'Institutional Infrastructure', color: '#A64B42', order: 5 },
    { id: 'recognition', label: 'Assessment, Recognition & Impact', color: '#6A5ACD', order: 6 },
  ],
  processes: [
    { id: 'urban-mission', domainId: 'urban', label: 'Urban Mission', startYear: 1968, endYear: 2026, continues: true, importance: 'primary' },
    { id: 'engaged-pedagogy', domainId: 'pedagogy', label: 'Engaged Pedagogy', startYear: 1993, endYear: 2026, continues: true, importance: 'primary' },
    { id: 'neighborhood-partnerships', domainId: 'neighborhood', label: 'Neighborhood Partnerships', startYear: 1997, endYear: 2026, continues: true, importance: 'primary' },
    { id: 'public-scholarship', domainId: 'scholarship', label: 'Public Scholarship', startYear: 2004, endYear: 2026, continues: true, importance: 'primary' },
    { id: 'institutional-infrastructure', domainId: 'infrastructure', label: 'Institutional Infrastructure', startYear: 1994, endYear: 2026, continues: true, importance: 'primary' },
    { id: 'recognition-impact', domainId: 'recognition', label: 'Recognition & Impact Systems', startYear: 2006, endYear: 2026, continues: true, importance: 'primary' },
  ],
  anchors: [
    { id: 'lugar-1968', label: 'Mayor Lugar calls for urban university', year: 1968, processId: 'urban-mission', domainId: 'urban', importance: 'major', confidence: 'confirmed', visibleLabel: true },
    { id: 'iupui-1969', label: 'IUPUI established', year: 1969, processId: 'urban-mission', domainId: 'urban', importance: 'major', confidence: 'confirmed', visibleLabel: true },
    { id: 'philanthropy-1987', label: 'Center on Philanthropy established', year: 1987, processId: 'urban-mission', domainId: 'urban', importance: 'supporting', confidence: 'confirmed', visibleLabel: false },
    { id: 'osl-1993', label: 'Office of Service-Learning established', year: 1993, processId: 'engaged-pedagogy', domainId: 'pedagogy', importance: 'major', confidence: 'confirmed', visibleLabel: true },
    { id: 'csl-1994', label: 'Center for Service and Learning established', year: 1994, processId: 'institutional-infrastructure', domainId: 'infrastructure', importance: 'major', confidence: 'confirmed', visibleLabel: true },
    { id: 'wesco-1997', label: 'WESCO partnership', year: 1997, processId: 'neighborhood-partnerships', domainId: 'neighborhood', importance: 'major', confidence: 'confirmed', visibleLabel: true },
    { id: 'onr-1997', label: 'Office of Neighborhood Resources established', year: 1997, processId: 'institutional-infrastructure', domainId: 'infrastructure', importance: 'major', confidence: 'confirmed', visibleLabel: false },
    { id: 'gwchs-2000', label: 'George Washington Community High School reopens', year: 2000, processId: 'neighborhood-partnerships', domainId: 'neighborhood', importance: 'major', confidence: 'confirmed', visibleLabel: true },
    { id: 'public-scholar-2004', label: 'First Public Scholar faculty hire', year: 2004, processId: 'public-scholarship', domainId: 'scholarship', importance: 'major', confidence: 'confirmed', visibleLabel: true },
    { id: 'carnegie-2006', label: 'Carnegie Community Engagement Classification', year: 2006, processId: 'recognition-impact', domainId: 'recognition', importance: 'major', confidence: 'confirmed', visibleLabel: true },
    { id: 'oce-2014', label: 'Office of Community Engagement consolidated', year: 2014, processId: 'institutional-infrastructure', domainId: 'infrastructure', importance: 'major', confidence: 'confirmed', visibleLabel: true },
    { id: 'public-scholars-2015', label: 'Public Scholars Working Group', year: 2015, processId: 'public-scholarship', domainId: 'scholarship', importance: 'supporting', confidence: 'probable', visibleLabel: false },
    { id: 'collaboratory-2017', label: 'Collaboratory adopted', year: 2017, processId: 'institutional-infrastructure', domainId: 'infrastructure', importance: 'major', confidence: 'confirmed', visibleLabel: true },
    { id: 'rubric-2018', label: 'Public scholarship rubric developed', year: 2018, processId: 'recognition-impact', domainId: 'recognition', importance: 'major', confidence: 'probable', visibleLabel: true },
    { id: 'engage-2019', label: 'ENGAGE! journal launched', year: 2019, processId: 'public-scholarship', domainId: 'scholarship', importance: 'major', confidence: 'confirmed', visibleLabel: true },
    { id: 'iu-indianapolis-2024', label: 'IU Indianapolis realignment', year: 2024, processId: 'urban-mission', domainId: 'urban', importance: 'major', confidence: 'confirmed', visibleLabel: true },
    { id: 'centr-2024', label: 'CEnTR ecosystem matures', year: 2024, processId: 'institutional-infrastructure', domainId: 'infrastructure', importance: 'supporting', confidence: 'probable', visibleLabel: false },
    { id: 'carnegie-renewal-2026', label: 'Carnegie renewal / impact framework', year: 2026, processId: 'recognition-impact', domainId: 'recognition', importance: 'major', confidence: 'needs-verification', visibleLabel: true },
  ],
  interactions: [
    { id: 'urban-enables-pedagogy', fromId: 'urban-mission', fromType: 'process', toId: 'engaged-pedagogy', toType: 'process', verb: 'creates civic context for', strength: 'strong', confidence: 'interpretive' },
    { id: 'neighborhood-shapes-pedagogy', fromId: 'neighborhood-partnerships', fromType: 'process', toId: 'engaged-pedagogy', toType: 'process', verb: 'shapes practice in', strength: 'strong', confidence: 'interpretive' },
    { id: 'pedagogy-enables-scholarship', fromId: 'engaged-pedagogy', fromType: 'process', toId: 'public-scholarship', toType: 'process', verb: 'provides precedent for', strength: 'moderate', confidence: 'interpretive' },
    { id: 'carnegie-drives-documentation', fromId: 'carnegie-2006', fromType: 'anchor', toId: 'collaboratory-2017', toType: 'anchor', verb: 'creates documentation pressure for', strength: 'moderate', confidence: 'interpretive' },
    { id: 'public-scholarship-to-engage', fromId: 'public-scholarship', fromType: 'process', toId: 'engage-2019', toType: 'anchor', verb: 'creates publication need for', strength: 'moderate', confidence: 'interpretive' },
    { id: 'infrastructure-supports-impact', fromId: 'institutional-infrastructure', fromType: 'process', toId: 'recognition-impact', toType: 'process', verb: 'enables measurement of', strength: 'strong', confidence: 'interpretive' },
  ],
  sources: [],
  settings: {
    activeView: 'process',
    showEras: true,
    showMinorAnchors: false,
    showInteractionLabels: true,
    showOnlyMajorInteractions: false,
    exportTheme: 'light',
  },
}
